version: '3.8'
name: Hackathon
services:
  postgres:
    image: postgres:16
    container_name: postgres_hackathon
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:${POSTGRES_PORT}"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - hackathon-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  hackathon-network:
    driver: bridge