name: Hackathon
services:
  postgres:
    image: postgres:16
    container_name: postgres_hackathon
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  authservice:
    build:
      context: . # Контекст сборки - корень проекта
      dockerfile: AuthService/Dockerfile # Путь к Dockerfile вашего сервиса
    env_file:
      - .env 
    ports:
      - "8012:80"   # Хост 8080 -> Контейнер 80 (HTTP)
      - "8011:443"
    container_name: AuthService
    environment:
      - ASPNETCORE_ENVIRONMENT=Development # Или Development, как вам нужно
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - ROLES=${ROLES}
      - JwtSettings__SecretKey=${JwtSettings__SecretKey}
      - JwtSettings__Issuer=${JwtSettings__Issuer}
      - JwtSettings__Audience=${JwtSettings__Audience}
      - JwtSettings__DurationInHours=${JwtSettings__DurationInHours}
      
      # Настройки для HTTPS
      - ASPNETCORE_URLS=http://+:80;https://+:443 # Kestrel будет слушать оба порта
      - KESTREL_CERTIFICATE_PASSWORD=${KESTREL_CERT_PASSWORD} # Ссылка на переменную из .env
    depends_on:
      - postgres


  gateway:
    build:
      context: . # Контекст сборки - корень проекта
      dockerfile: HackathonGateway/HackathonGateway/Dockerfile # Путь к Dockerfile вашего сервиса
    env_file:
     - .env
    container_name: Gateway
    ports:
      - "8000:80"   # Хост 8080 -> Контейнер 80 (HTTP)
      - "8001:443"  # Хост 8443 -> Контейнер 443 (HTTPS)
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - JwtSettings__SecretKey=${JwtSettings__SecretKey}
      - JwtSettings__Issuer=${JwtSettings__Issuer}
      - JwtSettings__Audience=${JwtSettings__Audience}
      - JwtSettings__DurationInHours=${JwtSettings__DurationInHours}
      # Настройки для HTTPS
      - ASPNETCORE_URLS=http://+:80;https://+:443 # Kestrel будет слушать оба порта
      - KESTREL_CERTIFICATE_PASSWORD=${KESTREL_CERT_PASSWORD} # Ссылка на переменную из .env
    depends_on:
      - authservice
