name: Hackathon
services:
  postgres:
    image: postgres:16
    container_name: postgres_hackathon
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  authservice:
    build:
      context: . # Контекст сборки - корень проекта
      dockerfile: AuthService/Dockerfile # Путь к Dockerfile вашего сервиса
    env_file:
      - .env 
    ports:
      - "8012:80"   # Хост 8012 -> Контейнер 80 (HTTP)
      - "8011:443"  # Хост 8011 -> Контейнер 443 (HTTPS)
    container_name: AuthService
    environment:
      - ASPNETCORE_ENVIRONMENT=Development # Или Development, как вам нужно
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - ROLES=${ROLES}
      - JwtSettings__SecretKey=${JwtSettings__SecretKey}
      - JwtSettings__Issuer=${JwtSettings__Issuer}
      - JwtSettings__Audience=${JwtSettings__Audience}
      - JwtSettings__DurationInHours=${JwtSettings__DurationInHours}
      # Настройки для HTTPS
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - KESTREL_CERTIFICATE_PASSWORD=${KESTREL_CERT_PASSWORD}
      # CORS настройки
      - AllowedOrigins__0=http://localhost:3010
      - AllowedOrigins__1=http://localhost:3000
      - AllowedOrigins__2=http://localhost:8000
      - AllowedOrigins__3=http://localhost:8001
      - AllowedOrigins__4=http://authservicefrontend
      - AllowedOrigins__5=http://frontend
      - AllowedOrigins__6=http://gateway
       # Настройки для HTTPS
    volumes:
      - ./cert.pfx:/app/cert.pfx
    depends_on:
      - postgres
  gateway:
    build:
      context: . # Контекст сборки - корень проекта
      dockerfile: HackathonGateway/HackathonGateway/Dockerfile # Путь к Dockerfile вашего сервиса
    env_file:
      - .env
    container_name: Gateway
    ports:
      - "8000:80"   # Хост 8080 -> Контейнер 80 (HTTP)
      - "8001:443"  # Хост 8443 -> Контейнер 443 (HTTPS)
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - JwtSettings__SecretKey=${JwtSettings__SecretKey}
      - JwtSettings__Issuer=${JwtSettings__Issuer}
      - JwtSettings__Audience=${JwtSettings__Audience}
      - JwtSettings__DurationInHours=${JwtSettings__DurationInHours}
      # Настройки для HTTPS
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - KESTREL_CERTIFICATE_PASSWORD=${KESTREL_CERT_PASSWORD}
      # CORS настройки
      - AllowedOrigins__0=http://localhost:3010
      - AllowedOrigins__1=http://localhost:3000
      - AllowedOrigins__2=http://authservicefrontend
      - AllowedOrigins__3=http://frontend
    volumes:
      - ./cert.pfx:/app/cert.pfx
    depends_on:
      - authservice
    
  soundservice:
    build:
      context: .
      dockerfile: SoundService/SoundService/Dockerfile
    env_file:
      - .env
    container_name: SoundService
    ports: 
      - "8020:80"
      #- "8021:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      # Настройки для HTTPS
      - ASPNETCORE_URLS=http://+:80; #https://+:443
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - ROLES=${ROLES}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - ELASTIC_URI=${ELASTIC_URI}

  frontend:
    build:
      context: . # Контекст сборки - корень проекта
      dockerfile: FrontendService/Dockerfile
    container_name: Frontend
    ports:
      - "3000:80"   # Хост 3000 -> Контейнер 80 (HTTP)
    depends_on:
      - gateway
      - postgres
      - elasticsearch
      - minio

  authservicefrontend:
    build:
      context: . # Контекст сборки - корень проекта
      dockerfile: AuthServiceFrontend/Dockerfile
    container_name: AuthServiceFrontend
    restart: always
    ports:
      - "3010:80"   # Хост 3010 -> Контейнер 80 (HTTP)
    depends_on:
      - authservice
      - gateway

  elasticsearch:
    image: elasticsearch:8.17.3
    container_name: elastic
    restart: unless-stopped
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enrollment.enabled=false
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
      - ./logs/elasticsearch:/usr/share/elasticsearch/logs

  kibana:
    image: kibana:8.17.3
    container_name: kibana_hackaton
    restart: unless-stopped
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - node.name=kibana
      - cluster=es-docker-cluster
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address :9001

  mc-init:
    image: minio/mc
    container_name: mc-init
    depends_on:
      - minio
    volumes:
      # Эта строка отвечает за то, чтобы содержимое вашей папки
      # ./music_test/original_tracks на хосте было доступно
      # внутри контейнера mc-init по пути /init-audio
      - ./music_test/:/init-audio
    entrypoint: |
      /bin/sh -c "
        echo 'Ожидание MinIO...'
        sleep 8 # Можно немного увеличить sleep для надежности, если MinIO стартует медленно

        echo 'Настройка mc клиента...'
        mkdir -p /root/.mc
        # Убедитесь, что accessKey и secretKey здесь совпадают с MINIO_ROOT_USER/PASSWORD
        # или используйте переменные окружения для mc alias set, как предлагалось ранее
        echo '{\"version\": \"9\", \"hosts\": {\"local\": {
          \"url\": \"http://minio:9000\",
          \"accessKey\": \"minioadmin\",
          \"secretKey\": \"minioadmin\",
          \"api\": \"S3v4\"
        }}}' > /root/.mc/config.json

        echo 'Создание бакета local/audio-bucket (если не существует)...'
        mc mb --ignore-existing local/audio-bucket

        echo '🔄 Зеркалирую все содержимое /init-audio/ в local/audio-bucket/ сохраняя структуру...'
        # Ключевая команда: mc mirror
        # --overwrite перезапишет существующие файлы в бакете, если они есть и в источнике
        # Если нужно, чтобы удалялись файлы в бакете, которых нет в источнике, добавьте --remove
        mc mirror --overwrite /init-audio/ local/audio-bucket/

        # Проверка: вывести список файлов в бакете для отладки
        echo 'Содержимое бакета local/audio-bucket/ после зеркалирования:'
        mc ls --recursive local/audio-bucket/

        if [ $? -eq 0 ]; then
          echo '✅ Процесс зеркалирования успешно завершен.'
        else
          echo '❌ Ошибка во время выполнения mc mirror или mc ls.'
        fi
      "